server:
  port: 9092

#eureka:
#  instance:
#    hostname: localhost
#    port: 9091
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: ekklesia
            client-secret: ekklesia-client
            resource-ids: resources
            grant_type: password
            scope: read,write

spring:
    datasource:
        data: classpath:/sql/data.sql
        driver-class-name: org.postgresql.Driver
        platform: h2
        url: jdbc:postgresql://obyxmfxxnqdfhx:0f831a79056f06183406599f7b2b20cacd68f2096a0eb625bb4fe0ad42a21aa4@ec2-54-235-240-126.compute-1.amazonaws.com:5432/d7i1e63qsvllle
        username: obyxmfxxnqdfhx
        password: 0f831a79056f06183406599f7b2b20cacd68f2096a0eb625bb4fe0ad42a21aa4
        schema: classpath:/sql/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
