server:
  port: 9093

#eureka:
#  instance:
#    hostname: localhost
#    port: 9091
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
# server:
#    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: 
        platform: org.hibernate.dialect.H2Dialect
        url: jdbc:h2:file:~/cadastro-membro
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
